### ISSUE TITLE
Cannot use songs folder that is outside the osu! directory

### ISSUE THREAD

**Issue by Kuuuube** [Xarib/OsuMapMatcher#3]
Currently my songs folder is set to `C:\o` and my osu! directory is in `%localappdata%\osu!`

Trying to add `C:\o` as my songs directory throws the following errors:

Trying to change the settings using the web tool: `Invalid Song Path`
When editing the settings file manually I get the following output from the cmd window: `Song folder not found!`
Upon launching osu! and selecting a map: `Song folder not found! Go to settings and set the correct path.`

My `C:\o` directory contains the same file structure that any other songs folder would. The only difference is it isn't in my osu! folder.

I also tested using another client with the songs folder in the osu! folder and it works as expected.

**Comment by Xarib** [comment]
Good news! I can replicate your issue. I'm going to fix it soon. If you still can't wait, you have to rename the `o` directory to `Songs`.
