### ISSUE TITLE
Source for calculation algorithms

### ISSUE THREAD

**Issue by Kuuuube** [Xarib/OsuMapMatcher#4]
Seeing as the project has been discontinued it would be nice to have this. It would be a shame for it to be lost.

I realize it probably won't be user friendly and could be a mess but this seems like a cool tool. It would be nice to allow the possibility for someone else to run their own or for the calculations to be used elsewhere.

**Comment by Xarib** [comment]
Made my [processing library](https://github.com/Xarib/OsuFileIO) public. For this project I used a different analyzer but the new one should be similar. Currently only osu!std maps work.

**Comment by Kuuuube** [comment]
Thank you!
